apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  namespace: pet-clinic-app
spec:
  # type: NodePort
  type: ClusterIP
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      # nodePort: 31000
